
raw_data_path: data/raw_data/Womens Clothing E-Commerce Reviews.csv

all_path: data/processed_data/all_reviews.csv
young_path: data/processed_data/young_reviews.csv
model_path: model/bert_model

mlflow_url: https://dagshub.com/eugenia.anello/topic-modeling-reviews.mlflow
MLFLOW_TRACKING_USERNAME: eugenia.anello
MLFLOW_TRACKING_PASSWORD: bd3592a38029adedb7da200ee3281176919c5d18    

DAGSHUB_REMOTE_URL: https://dagshub.com/eugenia.anello/topic-modeling-reviews
DVC_REMOTE_URL: https://dagshub.com/eugenia.anello/topic-modeling-reviews.dvc

model_already_trained: False
visualization_over: False

credentials: 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