name: ETL Train Save Model
on: [pull_request]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        env:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
        run: pip install -r requirements.txt

      - name: Data Preprocessing 
        run: python src/process_data.py

      - name: Model Training
        run: python src/train.py
        
      - name: Experiment Tracking
        run: python src/mlflow_log.py
