name: Training on EC2 selfhosted Runner
on: [push, pull_request]

jobs:
  deploy-runner: # (1) Deployment of the EC2 runner 
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Runner deployment on EC2 # (1.1) Start the deployment
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml runner \
              --cloud=aws \
              --cloud-region=us-east-1 \
              --cloud-type=t2.micro \
              --labels=cml-runner
  train-model: # (2) Training of the model 
    needs: deploy-runner 
    runs-on: [cml-runner] # (2.1) Specify the machine to use for training
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Model Training
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml ci
          pip install -r requirements.txt
          python src/process_data.py
          python src/train.py         
